CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98
NAME =  Form
SRC =	main.cpp\
		Bureaucrat.cpp\
		AForm.cpp\
		ShrubberyCreationForm.cpp\
		RobotomyRequestForm.cpp\
		PresidentialPardonForm.cpp

OBJ = ${SRC:.cpp=.o}

all: $(NAME)

$(NAME):	$(OBJ)
			${CC} ${CFLAGS} ${OBJ} -o ${NAME}
clean:
			rm -f ${OBJ}
fclean:		clean
			rm -f ${NAME}
re:			fclean all

.PHONY:		all clean fclean re